### PR TITLE
Include P2 Theme

### PR DESCRIPTION
**Pull request by jcheringer**
## Summary

This PR adds the P2 theme as a new theme option for the new Editor.

Depends on: D83496-code

## Test Instructions

* Apply D83496-code
* Create/edit a new project
* Use the available options to change the theme
* You should see the P2 theme as an option
* Select the P2 theme and play around with some blocks to make sure it looks good.

### CODE REVIEW

**Comment by jcheringer** [comment]
@digitalwaveride I think we'll need a better 'preview' image.
Added the image below just as a placeholder for now.

image

**Comment by digitalwaveride** [comment]
> I think we'll need a better 'preview' image.

Let's take the image from
https://wordpress.com/p2/

image


Which overall reminds me, we should change the preview images of all themes...

**Comment by digitalwaveride** [comment]
Super nice João!!! 
Thanks so much for bringing this over so quickly.

A few notes:

---
- [ ] Overall question blocks:

No grey background color. Please compare with Poll block in P2.

---
- [ ] Dropdown Block:

Chevron Icon needs on the right as much padding as text on the left: 
image

---
- [ ] Rating Block:

The blue border line is a bit too much … could we give it the same grey outline by default as the block itself has?
image

---
- [ ] Input Fields:

Please check field heights... at least 48 if you compare input fields in the contact form block in P2
Also please check the padding for the text inside the input fields. 

---
- [ ] Text Question Block / Template Case:

There seems to be some margin missing below. Just an issue in that specific "customer service feedback" template?
image

---

That's it! 🚀 Thx again João!

**Comment by jcheringer** [comment]
Hey @digitalwaveride! Thanks for taking a look.
I think I addressed all the comments.
Could you give it another spin, please? 🙏

**Review by digitalwaveride — APPROVED** [review]
Nice João!
Thank you!!!
🚀

**Pull request merged**
