### PR TITLE
Create File Upload block

### PR DESCRIPTION
**Pull request by jcheringer**
## Summary

This PR includes the File Upload block. 
It allows users to receive files from their respondents.

Depends on: D81916-code

## Test Instructions
* Apply D81916-code
* Create a project and add the brand new File Upload block
* Play with the sidebar settings to customize the block behavior
* Test it on the Renderer

## Screenshots

image

### CODE REVIEW

**Comment by TheSteveK** [comment]
Are we doing the banner to show free users that you have to pay us for this block?  I tried changing my account to free, but it still let me add the block, no problem.

**Review by ice9js — COMMENTED** [review]
Code is looking good, still need to give it a proper test run.

**Review by ice9js — COMMENTED** [review]
I gave this a test run and all seems good but I'm unable to view the file I submitted in the results. In fact, the question doesn't show up in the results at all (either as skipped or completed).

Am I doing anything wrong or is there a known issue?

**Review by ice9js — APPROVED** [review]
My bad, had a stale version of the branch checked out locally. All is well. :shipit:

**Pull request merged**
