### PR TITLE
Simplify matchRoute function

### PR DESCRIPTION
**Pull request by jcheringer**
## Summary

This is just a small refactor to make the code a bit cleaner and easy to read.

## Test instructions

We just need to make sure the Router is working as expected by navigating on the Editor and Project Renderer routes.

### CODE REVIEW

**Review by CGastrell — APPROVED** [review]
Works for me :) :shipit:

**Review by ice9js — CHANGES_REQUESTED** [review]
So actually, unfortunately this whole expression has broken the router.

`matchRoute` used to return `null` is no match is found when no match was found and the `<Route />` component depends on that behavior.

To be honest, the more I think about it, we should just revert #167 altogether.

`toNumber` works with different bases so for example `0b1` (pun intended) translates to `1`.  
The router is also used on our project renderer which uses hexadecimal project IDs which aren't converted to numbers as long as they're not prefixed with `0x` but hexadecimal values that happen to only contain digits in 0-9 range would still be converted to a decimal integer which while it might work is not entirely great either.

If anything, I guess the proper way would be to define the type on the route itself as sometimes even when the value is numeric, it's not necessarily meant to be a number. So I'd say let's remove it and just stick with strings for consistency - especially since we don't actually need this for anything?

**Comment by jcheringer** [comment]
> So actually, unfortunately this whole expression has broken the router.
> 
> `matchRoute` used to return `null` is no match is found when no match was found and the `<Route />` component depends on that behavior.
> 
> To be honest, the more I think about it, we should just revert #167 altogether.
> 
> `toNumber` works with different bases so for example `0b1` (pun intended) translates to `1`. The router is also used on our project renderer which uses hexadecimal project IDs which aren't converted to numbers as long as they're not prefixed with `0x` but hexadecimal values that happen to only contain digits in 0-9 range would still be converted to a decimal integer which while it might work is not entirely great either.
> 
> If anything, I guess the proper way would be to define the type on the route itself as sometimes even when the value is numeric, it's not necessarily meant to be a number. So I'd say let's remove it and just stick with strings for consistency - especially since we don't actually need this for anything?

Well, the idea here was to make things a bit simpler but, considering the time we spent discussing this solution and yet we didn't find a reliable solution, I'd say things are not getting simpler. 😅 
It's fine to me if we decide to discard this PR and revert the #167.

**Comment by ice9js** [comment]
Yeah, let's revert it  and postpone this until there actually is a need for it. Meanwhile we can continue the fun debate, lol.

**Pull request closed without merging**
