### PR TITLE
Remove top and bottom margins from elements inside columns on Renderer

### PR DESCRIPTION
**Pull request by jcheringer**
## Summary

This PR adds some style changes to keep consistency between what is presented on the Editor and on the Project Renderer.

Ref: c/jBovK6XC-tr

## Test Instructions
* Create a project and add a Columns block
* Add a few blocks inside the columns
* Compare the Editor and the Renderer
* They should look similar

### CODE REVIEW

**Review by TheSteveK — COMMENTED** [review]
Your code works, but there's still a lot of inconsistency between the editor and the preview.

Here was my first stab at it:
Screen Shot 2022-05-02 at 6 40 24 AM
Screen Shot 2022-05-02 at 6 40 33 AM

That appears to be more of a problem with the question block than your changes.  So I flipped it around and put the form fields on top:

Screen Shot 2022-05-02 at 6 43 32 AM

So it shows the margins are gone as you intended, but, maybe they're a little too small now as the blocks are sort of stacked very close together.

**Comment by jcheringer** [comment]
Thanks for taking a look @TheSteveK!
My first thought was to remove the margins for all blocks inside columns and leave it to the user to add margins using the `Spacer Block`, but this might not be intuitive.
Also, due to some CSS specificity, the change didn't work well for the Question Blocks, as you already noticed.
So, I made some changes aiming to handle both situations: Add a default margin for all blocks inside the `Columns Block` and make this margin apply to Question Blocks.
Could you take a look again, please? 🙏

**Comment by TheSteveK** [comment]
The margin looks good.  The question block is still annoying and shrinks from the size set in the editor.   I'm not sure if that's in scope for this PR, however
Screen Shot 2022-05-03 at 5 45 06 AM
Screen Shot 2022-05-03 at 5 45 22 AM

**Comment by jcheringer** [comment]
Yeah, though I think this difference is outside the scope of this PR, I found out the change was quite simple, so I decided to add it to this PR.
From what I saw, the issue is happening with the `Rating Question` block due to some bottom margin that exists in the Renderer but doesn't exist in the Editor.
It should be ready for another spin. 😃

**Review by TheSteveK — APPROVED** [review]
Much better!  🚢🚢

**Pull request merged**
