### PR TITLE
Include new Templates

### PR DESCRIPTION
**Pull request by jcheringer**
## Summary

This PR includes a few more project templates:

- Customer Satisfaction Survey
- Event Ticket Registration
- Joblisting – Application Flow
- Join our Community
- Join Waitlist

Ref: pabtAt-1Vr-p2#comment-2106

Fixes Automattic/crowdsignal#433

## Testing Instructions

* Open the project page and check if all the listed templates were added and work as expected

### CODE REVIEW

**Comment by TheSteveK** [comment]
Ok, slightly nit picky, but I think Joblisting should be two words :)

**Comment by TheSteveK** [comment]
Oh and while I'm making minor suggestions, you could use the URL form block instead of the text form block on the waitlist where it's asking for twitter and linkedin profile info

**Review by CGastrell — COMMENTED** [review]
For once, all new templates are there.

Then there's a couple of wee things:

- Any tricks to get "WordCamp" fitting better? Make image smaller or something?
image

- not sure this is something to address here, maybe @digitalwaveride can come to the rescue, but the right margin of the template list could use some space. Margin, shadow and scrollbar seem to be fighting for it
image

- at some point we introduced this behavior: the template browser actually renders the templates, and as each preview is a button, we have this complaint on the console
image

That last one is not a problem "per se", but something that builds up: we already got used to live with the editor's error messages and we should try and keep it clean when it comes to ours. Otherwise, we slowly naturalize the idea of errors there and, eventually, we don't pay attention to them anymore, with obvious consequences in the long term.
Not part of this change, but maybe some error boundary? Or remove buttons from all preview rendering?

**Comment by digitalwaveride** [comment]
Thanks for taking a look @CGastrell 🙏 !

Regarding the previews... as discussed with @jcheringer via Slack... basically all the previews are broken... don't show 1:1 the rendering in the editor.
The issue seems to be that the preview renderer can't stand "full-width" and "cover blocks".

It seems to be not an easy fix, so all cover designs need to be cleaned up regarding the issues mentioned above.

**Comment by jcheringer** [comment]
Just added on last template: **Team Member Onboarding Survey**

**Comment by digitalwaveride** [comment]
image

image

Anyone seeing these text field issues in the previews?

**Comment by digitalwaveride** [comment]
Also... 
image

Thought we had that fixed ... 🤔 
Linebreak in the headline and button....

**Comment by jcheringer** [comment]
That's what I'm seeing:
image

**Comment by digitalwaveride** [comment]
... ok, weird! Can you please check on Firefox?

If that looks all good there, please can you go into the WordCamp example, and make the headline smaller?
Thanks!

**Comment by jcheringer** [comment]
@digitalwaveride I may want to change the width of the columns to 60%/40% on the Event Registration Form template. That seems to give it enough room to fit the text.

**Comment by jcheringer** [comment]
Looking good for me on Firefox too.

**Comment by TheSteveK** [comment]
It looks good from my side.  I'll leave it to @digitalwaveride to give the seal of approval. 🦭

**Comment by jcheringer** [comment]
The Event Registration template should be ok now. Already pushed the columns width change.

**Review by digitalwaveride — APPROVED** [review]
Awesome João! 🚀🚀🚀🚀

**Pull request merged**
