### PR TITLE
Update Share Modal to include Embed Popup settings

### PR DESCRIPTION
**Pull request by jcheringer**
## Summary

This PR complements #311 and includes the necessary changes to allow the user to customize the Embed Popup settings through the Share Modal

Depends On: D86900-code

Fixes Automattic/crowdsignal#452

image

## Test Instructions

* Apply backend changes
* Open or create a project and make sure it's published
* Click the Share button
* You should be able to see the `Edit Appearance` button on the Embed Popup card
* Click the button and play with the settings
* The settings should be saved automatically as soon as you stop editing

### CODE REVIEW

**Review by TheSteveK — CHANGES_REQUESTED** [review]
I ran into a few issues.
 
First, the modal doesn't close when you click outside of it (also true for the embed card)

Second, I randomly ran into an issue where the popup "jitters" this is sporadic, but I noticed it first when I didn't change the popup size and layout which if I recall means a slight CSS adjustment will fix it.


https://user-images.githubusercontent.com/12895386/187680274-b91c4fdd-2aa6-4f74-b51c-17426498ac0e.mp4

Finally, when embedding the popup and embed card on a sandboxed site, the settings don't apply.  I don't know if this PR also covers the embed, I can test that later.  But in the below screenshot, the popup should be set to 800px wide, bottom right and the card was set to 1920x1080

Screen Shot 2022-08-31 at 8 35 55 AM

**Comment by jcheringer** [comment]
I also was able to embed it on a sandboxed site and see the settings being applied:

image

For the embed card, the settings already exist in the sidebar. 
They were implemented on a previous PR, and I expected them to be working
image
I just added a shortcut on the share modal.
If they're not working, I'd say it's not related to these changes, and I'd handle it on another PR.

And about the 'jittering' issue, is there a site where I can see the issue happening?
I didn't face this issue during the tests. I'd need to see it to be able to fix it.

**Comment by jcheringer** [comment]
Just realized something important:
This PR only affects saving/editing the settings for the Embed Popup.
If you want to see them working, you need to checkout #313 wich is complementary to #312

**Review by TheSteveK — APPROVED** [review]
🚀

**Pull request merged**
